export interface TListData {
  dj: Dj
  category: string
  secondCategory: string
  buyed: boolean
  price: number
  originalPrice: number
  discountPrice: any
  purchaseCount: number
  lastProgramName: string
  videos: any
  finished: boolean
  underShelf: boolean
  liveInfo: any
  playCount: number
  privacy: boolean
  icon: any
  manualTagsDTO: any
  descPicList: any
  intervenePicUrl: string
  picUrl: string
  intervenePicId: number
  dynamic: boolean
  picId: number
  subCount: number
  shortName: string
  categoryId: number
  taskId: number
  programCount: number
  lastProgramId: number
  feeScope: number
  lastProgramCreateTime: number
  radioFeeType: number
  name: string
  id: number
  desc: string
  createTime: number
  rcmdtext: string
  subed: boolean
}

export interface Dj {
  defaultAvatar: boolean
  province: number
  authStatus: number
  followed: boolean
  avatarUrl: string
  accountStatus: number
  gender: number
  city: number
  birthday: number
  userId: number
  userType: number
  nickname: string
  signature: string
  description: string
  detailDescription: string
  avatarImgId: number
  backgroundImgId: number
  backgroundUrl: string
  authority: number
  mutual: boolean
  expertTags: any
  experts: any
  djStatus: number
  vipType: number
  remarkName: any
  authenticationTypes: number
  avatarDetail: any
  backgroundImgIdStr: string
  avatarImgIdStr: string
  anchor: boolean
  avatarImgId_str: string
}
