export interface ITopList {
  subscribers: any[]
  subscribed: any
  creator: any
  artists: any
  tracks: any
  updateFrequency: string
  backgroundCoverId: number
  backgroundCoverUrl: any
  titleImage: number
  titleImageUrl: any
  englishTitle: any
  opRecommend: boolean
  recommendInfo: any
  socialPlaylistCover: any
  trackNumberUpdateTime: number
  adType: number
  subscribedCount: number
  cloudTrackCount: number
  userId: number
  createTime: number
  highQuality: boolean
  specialType: number
  coverImgId: number
  updateTime: number
  anonimous: boolean
  newImported: boolean
  trackUpdateTime: number
  trackCount: number
  coverImgUrl: string
  commentThreadId: string
  totalDuration: number
  privacy: number
  playCount: number
  description: string
  ordered: boolean
  tags: any[]
  status: number
  name: string
  id: number
  coverImgId_str: string
  ToplistType: string
}
